New json format changes
Reliability-Measures/flask_microservice pull request #14
Opened 2020-04-03 23:23 UTC by A-Baji

Changed kr20.py, pbcc.py, difficulty.py, score.py, and average.py for new json format.
Created analyzeTest.py:
 - Creates sorted list of items by item id
 - Calls other functions (microservices) with the sorted list as parameter
 - Returns a tuple of all test information

2020-04-04 00:13 UTC, farrukhshahzad commented
You need to fix application.py to use three params like you have for calculate_k20 function

2020-04-04 00:13 UTC, farrukhshahzad requested changes
Also fix the conflicts

2020-04-05 21:58 UTC, farrukhshahzad commented
I did some adjustment:

- Use standard json format (all lower case)
- Use config JSON for keys/literal in code
- Adjust Test functions to use common data
- Try to use lower case also for local valuables in code
- Follow PE8 guidelines (no line longer than 70, two lines b/w functions etc.)  https://www.python.org/dev/peps/pep-0008/

2020-04-05 21:59 UTC, farrukhshahzad approved these changes
See my fixes

2020-04-05 21:59 UTC, farrukhshahzad commented on pbcc.py
> +    return {'pbcc': pbccDict}
We should have end of line (enter)  after last line. It is recommended

2020-04-05 21:59 UTC, farrukhshahzad commented on test_functions.py
> +                        {"itemid": 1, "response": 0},
can  `itemid` be string or always numeric?

2020-04-05 22:13 UTC, farrukhshahzad commented on application.py
> +    """
Please follow this format for function documentation.

2020-04-05 22:26 UTC, A-Baji commented on test_functions.py
> +                        {"itemid": 1, "response": 0},
It should be numeric since its sorted by numerical order.

2020-04-05 22:36 UTC, merged